services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: flask-app:v1
    container_name: backend
    ports:
      - "2020:2020"
    environment:
      - DB_HOST=192.168.190.111
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=mtzi_dev
    networks:
      docker_network:
        ipv4_address: 192.168.15.10

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: web-app:v1
    container_name: frontend
    ports:
      - "8080:80"
    environment:
    - API_BASE_URL=http://192.168.15.10:2020
    networks:
      docker_network:
        ipv4_address: 192.168.15.17

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.15.0/24